CREATE DATABASE NHAHANG
GO

USE NHAHANG

CREATE TABLE KHACHHANG
(
    MAKHACHHANG VARCHAR(5) PRIMARY KEY,
    HOVATENLOT  NVARCHAR(50)  NOT NULL,
    TEN         NVARCHAR(50)  NOT NULL,
    DIACHI      NVARCHAR(255) NOT NULL,
    EMAIL       VARCHAR(50)   NOT NULL,
    DIENTHOAI   VARCHAR(10)   NOT NULL
)
GO

CREATE TABLE SANPHAM
(
    MASANPHAM  INT IDENTITY (1,1) PRIMARY KEY,
    TENSANPHAM NVARCHAR(50)  NOT NULL,
    MOTA       NVARCHAR(255) NOT NULL,
    SOLUONG    INT CHECK (SOLUONG >= 0),
    DONGIA     MONEY CHECK (DONGIA >= 0)
)
GO

CREATE TABLE HOADON
(
    MAHOADON     INT PRIMARY KEY,
    NGAYMUAHHANG DATE         NOT NULL,
    MAKHACHHANG  VARCHAR(5)   NOT NULL,
    TRANGTHAI    NVARCHAR(30) NOT NULL,
    FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG
)
GO

CREATE TABLE HOADONCHITIET
(
    MAHOADONCHITIET INT IDENTITY (1,1) PRIMARY KEY,
    MAHOADON        INT NOT NULL,
    MASANPHAM       INT NOT NULL,
    SOLUONG         INT NOT NULL,
    FOREIGN KEY (MAHOADON) REFERENCES HOADON,
    FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM
)
GO

-- Nhập dữ liệu bảng Khách hàng
INSERT INTO KHACHHANG(MAKHACHHANG, HOVATENLOT, TEN, DIACHI, EMAIL, DIENTHOAI)
VALUES ('KH001', N'Cao Văn', N'Chỉnh', N'Hạ Mỗ, Đan Phượng, Hà Nội', 'chinh@fpt.edu.vn', '0338878397');
INSERT INTO KHACHHANG(MAKHACHHANG, HOVATENLOT, TEN, DIACHI, EMAIL, DIENTHOAI)
VALUES ('KH002', N'Ngô Trung', N'Hiếu', N'xã Đại Hợp, huyện Kiến Thụy, TP Hải Phòng', 'hieunt@fpt.edu.vn', '0339731812');
INSERT INTO KHACHHANG(MAKHACHHANG, HOVATENLOT, TEN, DIACHI, EMAIL, DIENTHOAI)
VALUES ('KH003', N'Đỗ Xuân', N'Hiếu', N'Nhật Tiến, xã Trường Yên, Chương Mỹ, Hà Nội', 'hieudx@fpt.edu.vn', '0973967774');
INSERT INTO KHACHHANG(MAKHACHHANG, HOVATENLOT, TEN, DIACHI, EMAIL, DIENTHOAI)
VALUES ('KH004', N'Đinh Viết', N'Khang', N'xã Yên Hợp, Quỳ Hợp, Nghệ An', 'khangdv@fpt.edu.vn', '0338269641');
INSERT INTO KHACHHANG(MAKHACHHANG, HOVATENLOT, TEN, DIACHI, EMAIL, DIENTHOAI)
VALUES ('KH005', N'Hà Thị', N'Ngọc Hải', N'Hạ Đình, Thanh Xuân, Hà Nội', 'haihtn@fpt.edu.vn', '0941889768');
GO

-- Nhập dữ liệu bảng Sản phẩm
INSERT INTO SANPHAM(TENSANPHAM, MOTA, SOLUONG, DONGIA)
OUTPUT INSERTED.MASANPHAM
VALUES (N'Bột Bakers Choice số 13 ( Bột làm bánh mỳ) - 1kg',N'Bột có hàm lượng protein cao 13 %, thường dùng chủ yếu để làm bảnh mì hay đế bánh pizzza',254,28000);
INSERT INTO SANPHAM(TENSANPHAM, MOTA, SOLUONG, DONGIA)
OUTPUT INSERTED.MASANPHAM
VALUES (N'Bột Bakers Choice số 8 ( Bột bánh Bông lan) - 1kg',N'Được làm từ lúa mì có hàm lượng gluten thấp (7.5 - 9%), được dùng làm các loại bánh ngọt có độ xốp nở',136,28000);
INSERT INTO SANPHAM(TENSANPHAM, MOTA, SOLUONG, DONGIA)
OUTPUT INSERTED.MASANPHAM
VALUES (N'Bột Bakers Choice số 11 ( bột mì đa dụng ) - 1kg',N'Có hàm lượng protein khoảng 10-12%, được dùng để làm các loạị bánh ngọt như gato hay gatuxe...',356,28000);
INSERT INTO SANPHAM(TENSANPHAM, MOTA, SOLUONG, DONGIA)
OUTPUT INSERTED.MASANPHAM
VALUES (N'Bột mỳ Meizan 500g',N'Loại bột mì đa dụng dùng trong làm bánh cupcake hay bánh ngọt',421,12000);
INSERT INTO SANPHAM(TENSANPHAM, MOTA, SOLUONG, DONGIA)
OUTPUT INSERTED.MASANPHAM
VALUES (N'Bột mỳ hoa ngọc lan 1kg',N'Hàm lượng protein (10-11%), VitaminB1. Thường dùng làm các loại bánh như bánh mỳ, bánh gatom bánh Trung thu...',124,22000);
GO

-- Nhập dữ liệu bảng Hoá đơn
INSERT INTO HOADON(MAHOADON, NGAYMUAHHANG, MAKHACHHANG, TRANGTHAI)
VALUES (111,'2021-11-30','KH001',N'Đã thanh toán');
INSERT INTO HOADON(MAHOADON, NGAYMUAHHANG, MAKHACHHANG, TRANGTHAI)
VALUES (222,'2021-12-31','KH002',N'Đã thanh toán');
INSERT INTO HOADON(MAHOADON, NGAYMUAHHANG, MAKHACHHANG, TRANGTHAI)
VALUES (333,'2022-01-09','KH003',N'Đã thanh toán');
INSERT INTO HOADON(MAHOADON, NGAYMUAHHANG, MAKHACHHANG, TRANGTHAI)
VALUES (444,'2022-01-10','KH004',N'Chưa thanh toán');
INSERT INTO HOADON(MAHOADON, NGAYMUAHHANG, MAKHACHHANG, TRANGTHAI)
VALUES (555,'2022-01-11','KH005',N'Chưa thanh toán');
GO

-- Nhập dữ liệu bảng Hoá đơn chi tiết
INSERT INTO HOADONCHITIET(MAHOADON, MASANPHAM, SOLUONG)
OUTPUT INSERTED.MAHOADONCHITIET
VALUES (111,1,10);
INSERT INTO HOADONCHITIET(MAHOADON, MASANPHAM, SOLUONG)
OUTPUT INSERTED.MAHOADONCHITIET
VALUES (222,3,20);
INSERT INTO HOADONCHITIET(MAHOADON, MASANPHAM, SOLUONG)
OUTPUT INSERTED.MAHOADONCHITIET
VALUES (333,2,5);
INSERT INTO HOADONCHITIET(MAHOADON, MASANPHAM, SOLUONG)
OUTPUT INSERTED.MAHOADONCHITIET
VALUES (444,1,20);
INSERT INTO HOADONCHITIET(MAHOADON, MASANPHAM, SOLUONG)
OUTPUT INSERTED.MAHOADONCHITIET
VALUES (555,5,15);
GO

SELECT * FROM KHACHHANG
SELECT * FROM SANPHAM
SELECT * FROM HOADON
SELECT * FROM HOADONCHITIET