CREATE DATABASE TEST
GO

USE TEST
GO

CREATE TABLE PHONGBAN
(
    TENPHG      nvarchar(50) NOT NULL,
    MAPHG       int PRIMARY KEY,
    TRPHG       nvarchar(50) NULL,
    NG_NHANCHUC date         NOT NULL
)
GO

CREATE TABLE DIADIEM
(
    MAPHG   int,
    DIADIEM nvarchar(50),
    PRIMARY KEY (MAPHG, DIADIEM),
    FOREIGN KEY (MAPHG) REFERENCES PHONGBAN
)
GO

CREATE TABLE DEAN
(
    TENDEAN  nvarchar(50) NOT NULL,
    MADA     int PRIMARY KEY,
    DDIEM_DA nvarchar(50) NOT NULL,
    PHONG    int          NULL,
)
GO

CREATE TABLE CONGVIEC
(
    MADA          int NOT NULL,
    STT           int NOT NULL,
    TEN_CONG_VIEC nvarchar(50),
    PRIMARY KEY (MADA, STT),
    FOREIGN KEY (MADA) REFERENCES DEAN
)
GO

CREATE TABLE NHANVIEN
(
    HONV     nvarchar(50) NOT NULL,
    TENLOT   nvarchar(50) NOT NULL,
    TENNV    nvarchar(50) NOT NULL,
    MANV     nvarchar(50) PRIMARY KEY,
    DIACHI   nvarchar(50) NOT NULL,
    NGAYSINH datetime     NOT NULL,
    PHAI     nvarchar(50) NOT NULL,
    LUONG    float        NOT NULL,
    MA_NQL   nvarchar(50) NULL,
    MAPHG    int          NULL,
    FOREIGN KEY (MAPHG) REFERENCES PHONGBAN
)
GO

CREATE TABLE PHANCONG
(
    MANV     nvarchar(50) NOT NULL,
    MADA     int          NOT NULL,
    STT      int          NOT NULL,
    THOIGIAN float        NOT NULL,
    PRIMARY KEY (MANV, MADA, STT),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN,
    FOREIGN KEY (MADA, STT) REFERENCES CONGVIEC,
)
GO

CREATE TABLE THANNHAN
(
    MANV     nvarchar(50) NOT NULL,
    TENTN    nvarchar(50) NOT NULL,
    PHAI     nvarchar(50) NOT NULL,
    NGAYSINH char(10)     NOT NULL,
    QUANHE   nvarchar(50) NOT NULL,
    PRIMARY KEY (MANV, TENTN, QUANHE),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN
)
GO

-- Nhập dữ liệu bảng Phòng ban
INSERT INTO PHONGBAN(TENPHG, MAPHG, TRPHG, NG_NHANCHUC)
VALUES (N'Quản lý', 1, 006, '1971-06-19')
INSERT INTO PHONGBAN(TENPHG, MAPHG, TRPHG, NG_NHANCHUC)
VALUES (N'Điều hành', 4, 008, '1985-01-01')
INSERT INTO PHONGBAN(TENPHG, MAPHG, TRPHG, NG_NHANCHUC)
VALUES (N'Nghien Cứu', 5, 005, '1970-05-22')
INSERT INTO PHONGBAN(TENPHG, MAPHG, TRPHG, NG_NHANCHUC)
VALUES (N'IT', 6, 008, '1985-01-01')
GO

-- Nhập dữ liệu bảng Địa điểm
INSERT INTO DIADIEM(MAPHG, DIADIEM)
VALUES (1, N'TP HCM')
INSERT INTO DIADIEM(MAPHG, DIADIEM)
VALUES (4, N'Hà Nội')
INSERT INTO DIADIEM(MAPHG, DIADIEM)
VALUES (5, N'Nha Trang')
INSERT INTO DIADIEM(MAPHG, DIADIEM)
VALUES (5, N'TP HCM')
INSERT INTO DIADIEM(MAPHG, DIADIEM)
VALUES (5, N'Vũng Tàu')
GO

-- Nhập dữ liệu bảng Đề án
INSERT INTO DEAN(TENDEAN, MADA, DDIEM_DA, PHONG)
VALUES (N'Sản Phẩm X', 1, N'Vũng Tàu', 5)
INSERT INTO DEAN(TENDEAN, MADA, DDIEM_DA, PHONG)
VALUES (N'Sản Phảm Y', 2, N'Nha Trang', 5)
INSERT INTO DEAN(TENDEAN, MADA, DDIEM_DA, PHONG)
VALUES (N'Sản Phảm Z', 3, N'TP HCM', 5)
INSERT INTO DEAN(TENDEAN, MADA, DDIEM_DA, PHONG)
VALUES (N'Tin Học Hóa', 10, N'Hà Nội', 4)
INSERT INTO DEAN(TENDEAN, MADA, DDIEM_DA, PHONG)
VALUES (N'Cáp Quang', 20, N'TP HCM', 1)
INSERT INTO DEAN(TENDEAN, MADA, DDIEM_DA, PHONG)
VALUES (N'Đào Tạo', 30, N'Hà Nội', 4)
GO

-- Nhập dữ liệu bảng Công việc
INSERT INTO CONGVIEC(MADA, STT, TEN_CONG_VIEC)
VALUES (1, 1, N'Thiết kế sản phẩm X')
INSERT INTO CONGVIEC(MADA, STT, TEN_CONG_VIEC)
VALUES (1, 2, N'Thử nghiệm sản phẩm X')
INSERT INTO CONGVIEC(MADA, STT, TEN_CONG_VIEC)
VALUES (2, 1, N'Sản xuất sản phẩm Y')
INSERT INTO CONGVIEC(MADA, STT, TEN_CONG_VIEC)
VALUES (2, 2, N'Quảng cáo sản phẩm Y')
INSERT INTO CONGVIEC(MADA, STT, TEN_CONG_VIEC)
VALUES (3, 1, N'Khuyễn mãi sản phẩm Z')
INSERT INTO CONGVIEC(MADA, STT, TEN_CONG_VIEC)
VALUES (10, 1, N'Tin học hóa phòng nhân sự')
INSERT INTO CONGVIEC(MADA, STT, TEN_CONG_VIEC)
VALUES (10, 2, N'Tin học hóa phòng kinh doanh')
INSERT INTO CONGVIEC(MADA, STT, TEN_CONG_VIEC)
VALUES (20, 1, N'Lắp đặt cáp quang')
INSERT INTO CONGVIEC(MADA, STT, TEN_CONG_VIEC)
VALUES (30, 1, N'Đào tạo nhân viên Marketing')
INSERT INTO CONGVIEC(MADA, STT, TEN_CONG_VIEC)
VALUES (30, 2, N'Đào tạo nhân viên Thiết kế')
GO

-- Nhập dữ liệu bảng Nhân viên
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, DIACHI, NGAYSINH, PHAI, LUONG, MA_NQL, MAPHG)
VALUES (N'Đinh', N'Quỳnh', N'Như', 001, N'291 Hồ Văn Khuê, TP HCM', '1967-02-01', N'Nữ', 43000, 006, 4)
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, DIACHI, NGAYSINH, PHAI, LUONG, MA_NQL, MAPHG)
VALUES (N'Phan', N'Viet', N'The', 002, N'778 Nguyễn Kiệm, TP HCM', '1984-01-11', N'', 30000, 001, 4)
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, DIACHI, NGAYSINH, PHAI, LUONG, MA_NQL, MAPHG)
VALUES (N'Trần', N'Thanh', N'Tâm', 003, N'34 Mai Thị Lự, TP HCM', '1957-05-04', N'Nam', 25000, 005, 5)
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, DIACHI, NGAYSINH, PHAI, LUONG, MA_NQL, MAPHG)
VALUES (N'Nguyễn', N'Mạnh', N'Hùng', 004, N'95 Bà Rịa, Bà Rịa - Vũng Tàu', '1967-03-04', N'Nam', 38000, 005, 5)
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, DIACHI, NGAYSINH, PHAI, LUONG, MA_NQL, MAPHG)
VALUES (N'Nguyễn', N'Thanh', N'Tùng', 005, N'222 Nguyễn Văn Cừ, TP HCM', '1962-08-20', N'Nam', 40000, 006, 5)
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, DIACHI, NGAYSINH, PHAI, LUONG, MA_NQL, MAPHG)
VALUES (N'Phạm', N'Văn', N'Vinh', 006, N'15 Trưng Vương', '1965-01-01', N'Nữ', 55000, NULL, 1)
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, DIACHI, NGAYSINH, PHAI, LUONG, MA_NQL, MAPHG)
VALUES (N'Bùi', N'Ngọc', N'Hành', 007, N'332 Nguyễn Thái Học, TP HCM', '1954-03-11', N'Nam', 25000, 001, 4)
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, DIACHI, NGAYSINH, PHAI, LUONG, MA_NQL, MAPHG)
VALUES (N'Trần', N'Hồng', N'Quang', 008, N'80 Lê Hồng Phong, TP HCM', '1967-09-11', N'Nam', 25000, 001, 4)
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, DIACHI, NGAYSINH, PHAI, LUONG, MA_NQL, MAPHG)
VALUES (N'Đinh', N'Bá', N'Tiên', 009, N'119 Cống Quỳnh, TP HCM', '1960-02-11', N'N', 30000, 005, 5)
INSERT INTO NHANVIEN(HONV, TENLOT, TENNV, MANV, DIACHI, NGAYSINH, PHAI, LUONG, MA_NQL, MAPHG)
VALUES (N'Đinh', N'Bá', N'Tiên', 017, N'119 Cống Quỳnh, TP HCM', '1960-02-11', N'N', 30000, 005, 5)
GO

-- Nhập dữ liệu bảng Phân công
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (001, 20, 1, 15.321547)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (001, 30, 1, 20.5)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (003, 1, 2, 20)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (03, 2, 1, 20)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (004, 3, 1, 40.7)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (005, 3, 1, 10)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (005, 10, 2, 10)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (005, 20, 1, 10)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (006, 20, 1, 30)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (007, 10, 2, 10.7)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (007, 30, 2, 30)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (008, 10, 1, 35.2)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (008, 30, 2, 5)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (009, 1, 1, 32.54)
INSERT INTO PHANCONG(MANV, MADA, STT, THOIGIAN)
VALUES (009, 2, 2, 8.9)
GO

-- Nhập dữ liệu bảng Nhân thân
INSERT INTO THANNHAN(MANV, TENTN, PHAI, NGAYSINH, QUANHE)
VALUES (001, N'Minh', N'Nam', '1932-02-29', N'Vợ Chồng')
INSERT INTO THANNHAN(MANV, TENTN, PHAI, NGAYSINH, QUANHE)
VALUES (005, N'Khang', N'Nam', '1973-10-25', N'Con trai')
INSERT INTO THANNHAN(MANV, TENTN, PHAI, NGAYSINH, QUANHE)
VALUES (005, N'Phương', N'Nữ', '1948-05-03', N'Vợ Chồng')
INSERT INTO THANNHAN(MANV, TENTN, PHAI, NGAYSINH, QUANHE)
VALUES (005, N'Trinh', N'Nữ', '1976-04-05', N'Con Gái')
INSERT INTO THANNHAN(MANV, TENTN, PHAI, NGAYSINH, QUANHE)
VALUES (009, N'Châu', N'Nữ', '1978-09-30', N'Con Gái')
INSERT INTO THANNHAN(MANV, TENTN, PHAI, NGAYSINH, QUANHE)
VALUES (009, N'Phương', N'Nữ', '1975-05-05', N'Vợ Chồng')
INSERT INTO THANNHAN(MANV, TENTN, PHAI, NGAYSINH, QUANHE)
VALUES (009, N'Tiến', N'Nam', '1978-01-01', 'Con Trai')
INSERT INTO THANNHAN(MANV, TENTN, PHAI, NGAYSINH, QUANHE)
VALUES (017, N'Tiến', N'Nam', '1978-01-01', 'Con Trai')
GO

SELECT *
FROM PHONGBAN
SELECT *
FROM DIADIEM
SELECT *
FROM DEAN
SELECT *
FROM CONGVIEC
SELECT *
FROM NHANVIEN
SELECT *
FROM PHANCONG
SELECT *
FROM THANNHAN

-- Lương cao nhất
SELECT MAX(LUONG) 'Lương cao nhất'
FROM NHANVIEN

-- Luong trung bình
SELECT AVG(LUONG) 'Lương cao nhất'
FROM NHANVIEN
WHERE MAPHG = 4

-- Đếm số lượng Đề án tại HN
SELECT COUNT(*) 'Số lượng Dự án'
FROM DEAN
WHERE DDIEM_DA LIKE N'%Hà Nội%'

-- Số lượng nhân viên từng PB
SELECT MAPHG, COUNT(*) 'Số lượng NV'
FROM NHANVIEN
GROUP BY MAPHG

-- Lương cao nhất từng phòng ban
SELECT MAPHG, MAX(LUONG) 'Lương cao nhất'
FROM NHANVIEN
GROUP BY MAPHG
HAVING MAX(LUONG) > 50000

-- Lương trung bình từng phòng
SELECT MAPHG, AVG(LUONG) 'Trung bình lương'
FROM NHANVIEN
GROUP BY MAPHG

-- Tổng lương công ty phải trả cho từng PB,
-- chỉ hiển thị tổng > 80000
SELECT MAPHG, SUM(LUONG) 'Tổng lương'
FROM NHANVIEN
GROUP BY MAPHG
HAVING SUM(LUONG) > 80000

-- Tổng lương công ty phải trả cho từng PB,
-- chỉ nhóm cột có lương > 700
-- chỉ hiển thị tổng > 10000
SELECT MAPHG, SUM(LUONG) 'Tổng lương'
FROM NHANVIEN
WHERE LUONG > 30000
GROUP BY MAPHG
HAVING SUM(LUONG) > 50000

--
SELECT *
FROM NHANVIEN
ORDER BY TENNV

--
SELECT TENDEAN, DDIEM_DA
FROM DEAN
ORDER BY DDIEM_DA DESC

--
SELECT MAPHG 'Mã phòng ban', AVG(LUONG) 'Trung bình lương'
FROM NHANVIEN
WHERE LUONG > 30000
GROUP BY MAPHG
HAVING AVG(LUONG) > 35000
ORDER BY MAPHG DESC

-- SLIDE6
-- Truy vấn 2 bảng (Phép tích)
SELECT MANV, HONV + ' ' + TENLOT + ' ' + TENNV 'Tên nhân viên', NHANVIEN.MAPHG, TENPHG
FROM NHANVIEN,
     PHONGBAN
WHERE NHANVIEN.MAPHG = PHONGBAN.MAPHG

-- Truy vấn 3 bảng (Phép tích)
SELECT nv.MANV, HONV + ' ' + TENLOT + ' ' + TENNV 'Tên nhân viên', dA.MADA, TENDEAN, DDIEM_DA
FROM NHANVIEN AS nv,
     DEAN AS dA,
     PHANCONG AS pc
WHERE nv.MANV = pc.MANV
  AND dA.MADA = pc.MADA

-- Truy vấn 2 bảng (JOIN)
SELECT MANV, HONV + ' ' + TENLOT + ' ' + TENNV 'Tên nhân viên', A.MAPHG, TENPHG
FROM NHANVIEN A
     INNER JOIN PHONGBAN P ON P.MAPHG = A.MAPHG;

-- Truy vấn 3 bảng (Phép tích)
SELECT NHANVIEN.MANV, HONV + ' ' + TENLOT + ' ' + TENNV 'Tên nhân viên', DEAN.MADA, TENDEAN, DDIEM_DA
FROM NHANVIEN
     INNER JOIN PHANCONG ON NHANVIEN.MANV = PHANCONG.MANV
     INNER JOIN DEAN ON PHANCONG.MADA = DEAN.MADA

--Sử dụng JOIN hoặc phép tích để hiển thị thông tin của 3 bảng gồm:
-- họ và tên nhân viên, lương, tên phòng ban (Quản lý) mà nhân viên thuộc về, tên dự án địa điểm tại HN,

-- Do Không có nhân viên nào thỏa mãn điều kiện trên nên đổi thành PB(Điều hành), Địa điểm (HN)
SELECT NHANVIEN.MANV, HONV + ' ' + TENLOT + ' ' + TENNV 'Tên nhân viên', LUONG, TENDEAN
FROM NHANVIEN
     INNER JOIN PHANCONG ON NHANVIEN.MANV = PHANCONG.MANV
     INNER JOIN DEAN ON PHANCONG.MADA = DEAN.MADA
     INNER JOIN PHONGBAN ON NHANVIEN.MAPHG = PHONGBAN.MAPHG
WHERE TENPHG = N'Điều hành' AND DDIEM_DA  = N'Hà Nội'


SELECT *
FROM DEAN;