CREATE DATABASE QL_CONGTY -- Bài 1 (Lab4)
GO

USE QL_CONGTY
GO

CREATE TABLE VANPHONG
(
    MAVP        VARCHAR(10) NOT NULL,
    TRUONGPHONG NVARCHAR(30),
)
GO

CREATE TABLE DIADIEM
(
    MADD VARCHAR(10) NOT NULL,
    MAVP VARCHAR(10) NOT NULL,
)
GO

CREATE TABLE NHANVIEN
(
    MANV  VARCHAR(10)  NOT NULL,
    HOTEN NVARCHAR(30) NOT NULL,
    MAVP  VARCHAR(10)  NOT NULL,
)
GO

CREATE TABLE NHANTHAN
(
    HOTEN     NVARCHAR(30) NOT NULL,
    NGAYSINH  DATE,
    MOILIENHE NVARCHAR(15),
    MANV      VARCHAR(10)  NOT NULL,
)
GO

CREATE TABLE CHUSOHUU
(
    MACSH       VARCHAR(10)  NOT NULL,
    HOTEN       NVARCHAR(30) NOT NULL,
    DIACHI      NVARCHAR(100),
    SODIENTHOAI VARCHAR(10)  NOT NULL,
)

CREATE TABLE BDS
(
    MABDS  VARCHAR(10)   NOT NULL,
    TENBDS NVARCHAR(30),
    DIACHI NVARCHAR(100) NOT NULL,
    MAVP   VARCHAR(10)   NOT NULL,
    MACSH  VARCHAR(10)   NOT NULL,
)
GO


-- Thêm khoá chính & khoá ngoại
ALTER TABLE VANPHONG
    ADD CONSTRAINT KHOACHINHVP PRIMARY KEY (MAVP);

ALTER TABLE DIADIEM
    ADD CONSTRAINT KHOACHINHDD PRIMARY KEY (MADD);
ALTER TABLE DIADIEM
    ADD CONSTRAINT KHOANGOAIDD FOREIGN KEY (MAVP) REFERENCES VANPHONG;

ALTER TABLE NHANVIEN
    ADD CONSTRAINT KHOACHINHNV PRIMARY KEY (MANV);
ALTER TABLE NHANVIEN
    ADD CONSTRAINT KHOANGOAINV FOREIGN KEY (MAVP) REFERENCES VANPHONG;

ALTER TABLE NHANTHAN
    ADD CONSTRAINT KHOACHINHNT PRIMARY KEY (MANV, HOTEN);
ALTER TABLE NHANTHAN
    ADD CONSTRAINT KHOANGOAINT FOREIGN KEY (MANV) REFERENCES NHANVIEN;

ALTER TABLE CHUSOHUU
    ADD CONSTRAINT KHOACHINHCSH PRIMARY KEY (MACSH);

ALTER TABLE BDS
    ADD CONSTRAINT KHOACHINHBDS PRIMARY KEY (MABDS);
ALTER TABLE BDS
    ADD CONSTRAINT KHOANGOAIBDS1 FOREIGN KEY (MAVP) REFERENCES VANPHONG;
ALTER TABLE BDS
    ADD CONSTRAINT KHOANGOAIBDS2 FOREIGN KEY (MACSH) REFERENCES CHUSOHUU;

-- Thêm và xoá cột
ALTER TABLE NHANVIEN
    ADD EMAIL VARCHAR(30);
ALTER TABLE NHANVIEN
    ADD SODIENTHOAI VARCHAR(10);

ALTER TABLE NHANVIEN
    DROP COLUMN EMAIL;
ALTER TABLE NHANVIEN
    DROP COLUMN SODIENTHOAI;
