CREATE DATABASE QL_CONGTY -- Bài 1 (Lab4)
GO

USE QL_CONGTY
GO

CREATE TABLE VANPHONG
(
    MAVP        VARCHAR(10) NOT NULL,
    TRUONGPHONG VARCHAR(10) NOT NULL ,
)
GO

CREATE TABLE DIADIEM
(
    MADD VARCHAR(10) NOT NULL,
    MAVP VARCHAR(10) NOT NULL,
)
GO

CREATE TABLE NHANVIEN
(
    MANV  VARCHAR(10)  NOT NULL,
    HOTEN NVARCHAR(30) NOT NULL,
    MAVP  VARCHAR(10)  NOT NULL,
)
GO

CREATE TABLE NHANTHAN
(
    HOTEN     NVARCHAR(30) NOT NULL,
    NGAYSINH  DATE,
    MOILIENHE NVARCHAR(15),
    MANV      VARCHAR(10)  NOT NULL,
)
GO

CREATE TABLE CHUSOHUU
(
    MACSH       VARCHAR(10)  NOT NULL,
    HOTEN       NVARCHAR(30) NOT NULL,
    DIACHI      NVARCHAR(100),
    SODIENTHOAI VARCHAR(10)  NOT NULL,
)

CREATE TABLE BDS
(
    MABDS  VARCHAR(10)   NOT NULL,
    DIACHI NVARCHAR(100) NOT NULL,
    MAVP   VARCHAR(10)   NOT NULL,
    MACSH  VARCHAR(10)   NOT NULL,
)
GO


-- Thêm khoá chính
ALTER TABLE VANPHONG
    ADD CONSTRAINT VanPhong_PK PRIMARY KEY (MAVP);
ALTER TABLE DIADIEM
    ADD CONSTRAINT DiaDiem_PK PRIMARY KEY (MADD);
ALTER TABLE NHANVIEN
    ADD CONSTRAINT NhanVien_PK PRIMARY KEY (MANV);
ALTER TABLE NHANTHAN
    ADD CONSTRAINT NhanThan_PK PRIMARY KEY (MANV, HOTEN);
ALTER TABLE CHUSOHUU
    ADD CONSTRAINT ChuSoHuu_PK PRIMARY KEY (MACSH);
ALTER TABLE BDS
    ADD CONSTRAINT BDS_PK PRIMARY KEY (MABDS);


--  Thêm khoá ngoại
ALTER TABLE VANPHONG
    ADD CONSTRAINT VanPhong_FK FOREIGN KEY (TRUONGPHONG) REFERENCES NHANVIEN(MANV);
ALTER TABLE DIADIEM
    ADD CONSTRAINT DiaDiem_FK FOREIGN KEY (MAVP) REFERENCES VANPHONG;
ALTER TABLE NHANVIEN
    ADD CONSTRAINT NhanVien_FK FOREIGN KEY (MAVP) REFERENCES VANPHONG;
ALTER TABLE NHANTHAN
    ADD CONSTRAINT NhanThan_FK FOREIGN KEY (MANV) REFERENCES NHANVIEN;
ALTER TABLE BDS
    ADD CONSTRAINT BDS_FK1 FOREIGN KEY (MAVP) REFERENCES VANPHONG;
ALTER TABLE BDS
    ADD CONSTRAINT BDS_FK2 FOREIGN KEY (MACSH) REFERENCES CHUSOHUU;


-- Thêm và xoá cột
ALTER TABLE NHANVIEN
    ADD EMAIL VARCHAR(30);
ALTER TABLE NHANVIEN
    ADD SODIENTHOAI VARCHAR(10);

ALTER TABLE NHANVIEN
    DROP COLUMN EMAIL;
ALTER TABLE NHANVIEN
    DROP COLUMN SODIENTHOAI;