CREATE TABLE [dbo].[TACGIA_SACH] (
    [MASACH] VARCHAR (10) NOT NULL,
    [MATG]   VARCHAR (10) NOT NULL,
    PRIMARY KEY CLUSTERED ([MASACH] ASC, [MATG] ASC),
    FOREIGN KEY ([MASACH]) REFERENCES [dbo].[SACH] ([MASACH]),
    FOREIGN KEY ([MATG]) REFERENCES [dbo].[TACGIA] ([MATG])
);


GO

CREATE TABLE [dbo].[CTMUON] (
    [MASACH]  VARCHAR (10) NOT NULL,
    [SOPHIEU] INT          IDENTITY (1, 1) NOT NULL,
    PRIMARY KEY CLUSTERED ([MASACH] ASC, [SOPHIEU] ASC),
    FOREIGN KEY ([MASACH]) REFERENCES [dbo].[SACH] ([MASACH]),
    FOREIGN KEY ([SOPHIEU]) REFERENCES [dbo].[PHIEUMUON] ([SOPHIEU])
);


GO

CREATE TABLE [dbo].[CHUYENNGANH] (
    [MANGANH]  VARCHAR (10)  NOT NULL,
    [TENNGANH] NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([MANGANH] ASC)
);


GO

CREATE TABLE [dbo].[THELOAI] (
    [MATHELOAI]  VARCHAR (10)  NOT NULL,
    [TENTHELOAI] NVARCHAR (25) NULL,
    PRIMARY KEY CLUSTERED ([MATHELOAI] ASC)
);


GO

CREATE TABLE [dbo].[SINHVIEN] (
    [MASV]       VARCHAR (10)  NOT NULL,
    [TENSV]      NVARCHAR (50) NOT NULL,
    [MANGANH]    VARCHAR (10)  NOT NULL,
    [EMAIL]      VARCHAR (100) NOT NULL,
    [DIENTHOAI]  VARCHAR (10)  NOT NULL,
    [CMND]       VARCHAR (12)  NOT NULL,
    [NGAYHETHAN] DATE          NOT NULL,
    PRIMARY KEY CLUSTERED ([MASV] ASC),
    FOREIGN KEY ([MANGANH]) REFERENCES [dbo].[CHUYENNGANH] ([MANGANH])
);


GO

CREATE TABLE [dbo].[SACH] (
    [MASACH]    VARCHAR (10)   NOT NULL,
    [TENSACH]   NVARCHAR (50)  NOT NULL,
    [NXB]       NVARCHAR (100) NOT NULL,
    [SOTRANG]   INT            NULL,
    [SOLUONG]   INT            NULL,
    [GIATIEN]   MONEY          NULL,
    [NGAYNHAP]  DATE           NOT NULL,
    [VITRI]     NVARCHAR (25)  NOT NULL,
    [MATHELOAI] VARCHAR (10)   NULL,
    PRIMARY KEY CLUSTERED ([MASACH] ASC),
    CHECK ([GIATIEN]>(0)),
    CHECK ([SOLUONG]>(1)),
    CHECK ([SOTRANG]>(5)),
    FOREIGN KEY ([MATHELOAI]) REFERENCES [dbo].[THELOAI] ([MATHELOAI])
);


GO

CREATE TABLE [dbo].[TACGIA] (
    [MATG]  VARCHAR (10)  NOT NULL,
    [TENTG] NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([MATG] ASC)
);


GO

CREATE TABLE [dbo].[PHIEUMUON] (
    [SOPHIEU]    INT           IDENTITY (1, 1) NOT NULL,
    [MASV]       VARCHAR (10)  NOT NULL,
    [NGAYMUON]   DATE          NOT NULL,
    [NGAYTRA]    DATE          NULL,
    [TRANGTHAI]  NVARCHAR (50) NULL,
    [SOSACHMUON] INT           NULL,
    PRIMARY KEY CLUSTERED ([SOPHIEU] ASC),
    CHECK ([NGAYTRA]>[NGAYMUON]),
    CHECK ([SOSACHMUON]<=(3)),
    FOREIGN KEY ([MASV]) REFERENCES [dbo].[SINHVIEN] ([MASV])
);


GO

